// <auto-generated />
using System;
using CollegeAppDotnetWebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeAppDotnetWebApi.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240226113712_UptoCategoryCountUpdated")]
    partial class UptoCategoryCountUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CollegeAppDotnetWebApi.CategoryCountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChapterTestCount")
                        .HasColumnType("int");

                    b.Property<int>("NoteCount")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("VideoCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId")
                        .IsUnique();

                    b.ToTable("CategoryCountModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestDetailedDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChapterTestQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterTestUserDataId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserAnswerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterTestQuestionId");

                    b.HasIndex("ChapterTestUserDataId");

                    b.HasIndex("UserAnswerId");

                    b.ToTable("ChapterTestDetailedDataModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("TopicId");

                    b.ToTable("ChapterTestModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChapterTestQuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptionImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChapterTestQuestionId");

                    b.ToTable("ChapterTestOptionModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestQuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterTestId")
                        .HasColumnType("int");

                    b.Property<float>("NegativeMark")
                        .HasColumnType("float");

                    b.Property<float>("PositiveMark")
                        .HasColumnType("float");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SolutionImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterTestId");

                    b.ToTable("ChapterTestQuestionModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestUserDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChapterTestId")
                        .HasColumnType("int");

                    b.Property<int>("Correct")
                        .HasColumnType("int");

                    b.Property<int>("Incorrect")
                        .HasColumnType("int");

                    b.Property<float>("MarksObtained")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<float>("TotalMark")
                        .HasColumnType("float");

                    b.Property<int>("TotalQuestion")
                        .HasColumnType("int");

                    b.Property<int>("Unanswered")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterTestId");

                    b.HasIndex("StudentId");

                    b.ToTable("ChapterTestUserDataModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.CourseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("CourseModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.DiscussionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("Discussion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("TopicId");

                    b.HasIndex("CollegeId", "TopicId");

                    b.ToTable("DiscussionModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TestDuration")
                        .HasColumnType("int");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("SubjectId");

                    b.ToTable("LiveTestModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LiveTestQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptionImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LiveTestQuestionId");

                    b.ToTable("LiveTestOptionModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestQuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("LiveTestId")
                        .HasColumnType("int");

                    b.Property<int>("NegativeMark")
                        .HasColumnType("int");

                    b.Property<int>("PositiveMark")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SolutionImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("LiveTestId");

                    b.ToTable("LiveTestQuestionModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.NoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("TopicId");

                    b.ToTable("NoteModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.NoticeBoardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Notice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("Status");

                    b.ToTable("NoticeBoardModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.QueryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiscussionId")
                        .HasColumnType("int");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("StudentId");

                    b.ToTable("QueryModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.QuoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("QuoteModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.SubCourseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("SubCourseModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.SubjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("SubjectModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TejiloCollege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LocationUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ValidTill")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("TejiloCollege");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TejiloUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SubCourseId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("SubCourseId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TopicModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId", "Status");

                    b.ToTable("TopicModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.UserNoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("TopicId");

                    b.HasIndex("StudentId", "TopicId");

                    b.ToTable("UserNoteModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.VideoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("TotalVideoDuration")
                        .HasColumnType("int");

                    b.Property<string>("VdoCipherId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TopicId");

                    b.ToTable("VideoModel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NoticeBoardModelSubCourseModel", b =>
                {
                    b.Property<int>("NoticeBoardsId")
                        .HasColumnType("int");

                    b.Property<int>("SubCoursesId")
                        .HasColumnType("int");

                    b.HasKey("NoticeBoardsId", "SubCoursesId");

                    b.HasIndex("SubCoursesId");

                    b.ToTable("NoticeBoardModelSubCourseModel");
                });

            modelBuilder.Entity("SubCourseModelSubjectModel", b =>
                {
                    b.Property<int>("SubCoursesId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("int");

                    b.HasKey("SubCoursesId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("SubCourseModelSubjectModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.CategoryCountModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TopicModel", "TopicModel")
                        .WithOne("CategoryCountModel")
                        .HasForeignKey("CollegeAppDotnetWebApi.CategoryCountModel", "TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestDetailedDataModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.ChapterTestQuestionModel", "ChapterTestQuestion")
                        .WithMany()
                        .HasForeignKey("ChapterTestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.ChapterTestUserDataModel", "ChapterTestUserData")
                        .WithMany("ChapterTestDetailedData")
                        .HasForeignKey("ChapterTestUserDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.ChapterTestOptionModel", "UserAnswer")
                        .WithMany()
                        .HasForeignKey("UserAnswerId");

                    b.Navigation("ChapterTestQuestion");

                    b.Navigation("ChapterTestUserData");

                    b.Navigation("UserAnswer");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TopicModel", "Topic")
                        .WithMany("ChapterTests")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestOptionModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.ChapterTestQuestionModel", "ChapterTestQuestion")
                        .WithMany("Options")
                        .HasForeignKey("ChapterTestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterTestQuestion");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestQuestionModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.ChapterTestModel", "ChapterTest")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterTest");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestUserDataModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.ChapterTestModel", "ChapterTest")
                        .WithMany()
                        .HasForeignKey("ChapterTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", "TejiloUser")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterTest");

                    b.Navigation("TejiloUser");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.DiscussionModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TejiloCollege", "TejiloCollege")
                        .WithMany("Discussions")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", "TejiloUser")
                        .WithMany("Discussions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.TopicModel", "TopicModel")
                        .WithMany("Discussions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TejiloCollege");

                    b.Navigation("TejiloUser");

                    b.Navigation("TopicModel");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.SubjectModel", "Subject")
                        .WithMany("LiveTests")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestOptionModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.LiveTestQuestionModel", "LiveTestQuestion")
                        .WithMany("Options")
                        .HasForeignKey("LiveTestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiveTestQuestion");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestQuestionModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.LiveTestModel", "LiveTest")
                        .WithMany("Questions")
                        .HasForeignKey("LiveTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiveTest");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.NoteModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TopicModel", "Topic")
                        .WithMany("Notes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.NoticeBoardModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TejiloCollege", "TejiloCollege")
                        .WithMany("NoticeBoards")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TejiloCollege");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.QueryModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.DiscussionModel", "Discussion")
                        .WithMany("Queries")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", "TejiloUser")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discussion");

                    b.Navigation("TejiloUser");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.SubCourseModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.CourseModel", "Course")
                        .WithMany("SubCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TejiloUser", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TejiloCollege", "College")
                        .WithMany("Students")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.SubCourseModel", "SubCourse")
                        .WithMany()
                        .HasForeignKey("SubCourseId");

                    b.Navigation("College");

                    b.Navigation("SubCourse");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TopicModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.SubjectModel", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.UserNoteModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", "TejiloUser")
                        .WithMany("UserNotes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.TopicModel", "Topic")
                        .WithMany("UserNotes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TejiloUser");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.VideoModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TopicModel", "Topic")
                        .WithMany("Videos")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.TejiloUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoticeBoardModelSubCourseModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.NoticeBoardModel", null)
                        .WithMany()
                        .HasForeignKey("NoticeBoardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.SubCourseModel", null)
                        .WithMany()
                        .HasForeignKey("SubCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubCourseModelSubjectModel", b =>
                {
                    b.HasOne("CollegeAppDotnetWebApi.SubCourseModel", null)
                        .WithMany()
                        .HasForeignKey("SubCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeAppDotnetWebApi.SubjectModel", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestModel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestQuestionModel", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.ChapterTestUserDataModel", b =>
                {
                    b.Navigation("ChapterTestDetailedData");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.CourseModel", b =>
                {
                    b.Navigation("SubCourses");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.DiscussionModel", b =>
                {
                    b.Navigation("Queries");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestModel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.LiveTestQuestionModel", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.SubjectModel", b =>
                {
                    b.Navigation("LiveTests");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TejiloCollege", b =>
                {
                    b.Navigation("Discussions");

                    b.Navigation("NoticeBoards");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TejiloUser", b =>
                {
                    b.Navigation("Discussions");

                    b.Navigation("UserNotes");
                });

            modelBuilder.Entity("CollegeAppDotnetWebApi.TopicModel", b =>
                {
                    b.Navigation("CategoryCountModel")
                        .IsRequired();

                    b.Navigation("ChapterTests");

                    b.Navigation("Discussions");

                    b.Navigation("Notes");

                    b.Navigation("UserNotes");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
